//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLsach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGNO
    {
        public int MADL { get; set; }
        public int MAPX { get; set; }
        public int TIENNO { get; set; }
        public int TIENTRA { get; set; }
    
        public virtual DAILY DAILY { get; set; }
        public virtual PHIEUXUAT PHIEUXUAT { get; set; }
    }
}
