//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLsach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONGNO()
        {
            this.SACHBANDC = new HashSet<SACHBANDC>();
        }
    
        public int ID { get; set; }
        public int MADL { get; set; }
        public int MAPX { get; set; }
        public int TIENNO { get; set; }
        public int TIENTRA { get; set; }
    
        public virtual DAILY DAILY { get; set; }
        public virtual PHIEUXUAT PHIEUXUAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SACHBANDC> SACHBANDC { get; set; }
    }
}
