//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLsach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SachEntities : DbContext
    {
        public SachEntities()
            : base("name=SachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONGNO> CONGNO { get; set; }
        public virtual DbSet<CTPN> CTPN { get; set; }
        public virtual DbSet<CTPX> CTPX { get; set; }
        public virtual DbSet<DAILY> DAILY { get; set; }
        public virtual DbSet<MACDINH> MACDINH { get; set; }
        public virtual DbSet<NXB> NXB { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAP { get; set; }
        public virtual DbSet<PHIEUXUAT> PHIEUXUAT { get; set; }
        public virtual DbSet<SACH> SACH { get; set; }
        public virtual DbSet<SACHBANDC> SACHBANDC { get; set; }
        public virtual DbSet<TONKHO> TONKHO { get; set; }
    
    }
}
