//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLsach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHU
    {
        public int ID { get; set; }
        public System.DateTime NGAY { get; set; }
        public int MADL { get; set; }
        public int TIEN { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual DAILY DAILY { get; set; }
    }
}
